// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM2kT3d1-ozh-JLbpXXTysf4Pxux9a_x0',
    appId: '1:623453326249:web:19d787d0edecc7960212b8',
    messagingSenderId: '623453326249',
    projectId: 'elimu-cbd1d',
    authDomain: 'elimu-cbd1d.firebaseapp.com',
    storageBucket: 'elimu-cbd1d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLoSm70ezITW0QMIqTctTKOQfmSpvYX4s',
    appId: '1:623453326249:android:f2f6153d3f1710980212b8',
    messagingSenderId: '623453326249',
    projectId: 'elimu-cbd1d',
    storageBucket: 'elimu-cbd1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArwzonVokawh_3moehcWmFehetUU-Rczw',
    appId: '1:623453326249:ios:c8174dc0904695cb0212b8',
    messagingSenderId: '623453326249',
    projectId: 'elimu-cbd1d',
    storageBucket: 'elimu-cbd1d.firebasestorage.app',
    iosBundleId: 'com.example.elimu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArwzonVokawh_3moehcWmFehetUU-Rczw',
    appId: '1:623453326249:ios:c8174dc0904695cb0212b8',
    messagingSenderId: '623453326249',
    projectId: 'elimu-cbd1d',
    storageBucket: 'elimu-cbd1d.firebasestorage.app',
    iosBundleId: 'com.example.elimu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM2kT3d1-ozh-JLbpXXTysf4Pxux9a_x0',
    appId: '1:623453326249:web:d4be92608e944c790212b8',
    messagingSenderId: '623453326249',
    projectId: 'elimu-cbd1d',
    authDomain: 'elimu-cbd1d.firebaseapp.com',
    storageBucket: 'elimu-cbd1d.firebasestorage.app',
  );
}
